name: Backend Continuous Deployment
on:
  push:
    branches:
      - main
    paths:
      - "starter/backend/**"
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: backend
  PYTHON_VERSION: "3.10"
  REACT_APP_MOVIE_API_URL: http://localhost:5000
  WORKING_DIRECTORY: "starter/backend"

# A Continuous Deployment workflow that:
#     The built docker image should be tagged with the git sha
#     Runs a deploy job that applies the Kubernetes manifests to the provided cluster.
#     The manifest should deploy the newly created tagged image
#     ⚠️ NOTE Once you begin work on Continuous Deployment,
#       you'll need to first setup the AWS and Kubernetes environment.
#       Follow the next set of instructions when you're ready to start testing your deployments.

#     Accomplishes the following tasks:
#     Run after tests succeed
#     Tag the built docker image with the git sha (use GitHub Context)
#     If deploying to a Kubernetes cluster:
#     Push the image to ECR
#     Apply the Kubernetes manfiests using the image tag from build

# There should be a step that utilizes aws-actions/amazon-ecr-login action for logging into ECR.
# (using 3rd party actions)
# The ECR login step should also be accessing Github Secrets for credentials. (secure approach)
# There should be a step that pushes the docker image to ECR in the AWS account.
# There should be a step that deploys the application using kubectl to the kubernetes cluster
# The pipeline should be executed automatically on merges to the main branch
# The pipeline should be able to be run manually for verification purposes
# The pipeline should be running without errors with all tests passing
# and no output failures from any of the steps
# If there are AWS credentials anywhere in any of the pipelines = FAIL
# If any of the pipelines are failing to run or have failed steps = FAIL
# If any of the pipelines pass when there's a test failure = FAIL
# (will provide steps on how to simulate test failure)
# If the docker image doesn't get uploaded to ECR = FAIL
# If the application isn't successfully running on the cluster = FAIL
jobs:
  lint:
    name: Lint Job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pipenv"

      - name: Restore Cache
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: starter/backend
          key: ${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs['cache-hit'] != 'true'
        run: |
          pip install pipenv
          pipenv install flakes8

      - name: Run Lint
        run: pipenv run lint

  test:
    name: Test Job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pipenv"

      - name: Restore Cache
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: starter/backend
          key: ${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs['cache-hit'] != 'true'
        run: |
          pip install pipenv
          pipenv install

      - name: Run Test
        run: pipenv run test

  build_and_deploy:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --build-arg=REACT_APP_MOVIE_API_URL=${{ env.REACT_APP_MOVIE_API_URL }} --tag=$REPOSITORY:$IMAGE_TAG .
          docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker images
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Setup kubectl
        run: aws eks update-kubeconfig --name cluster --region ${{ env.AWS_REGION }}

      - name: Deploy the application using kubectl
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd k8s
          kustomize edit set image frontend=$REGISTRY/$REPOSITORY:$IMAGE_TAG
          kustomize build | kubectl apply -f -
