# A Continuous Deployment workflow that:
#     Runs on push against the main branch, only when code in the frontend application changes.
#     Is able to be run on-demand (i.e. manually without needing to push code)
#     Runs the same lint/test jobs as the Continuous Integration workflow
#     Runs a build job only when the lint and test jobs pass
#     The built docker image should be tagged with the git sha
#     Runs a deploy job that applies the Kubernetes manifests to the provided cluster.
#     The manifest should deploy the newly created tagged image
#
#     ⚠️ NOTE Once you begin work on Continuous Deployment,
#       you'll need to first setup the AWS and Kubernetes environment.
#       Follow the next set of instructions when you're ready to start testing your deployments.

# Build a Continuous Deployment pipeline for the backend application using Github Actions.
# The pipeline should be configured to meet the team's needs, fulfilling the requirements of linting,
#  testing, building and deploying of the application on every merge to the main branch.

#     Accomplishes the following tasks:
#     Run after tests succeed
#     Tag the built docker image with the git sha (use GitHub Context)
#     If deploying to a Kubernetes cluster:
#     Push the image to ECR
#     Apply the Kubernetes manfiests using the image tag from build

# There should be a step in the workflow that runs linting.
# There should be a step in the workflow that runs the tests
# There should be a step that builds the application using docker.
# There should be a step that utilizes aws-actions/amazon-ecr-login action for logging into ECR.
# (using 3rd party actions)
# The ECR login step should also be accessing Github Secrets for credentials. (secure approach)
# There should be a step that pushes the docker image to ECR in the AWS account.
# There should be a step that deploys the application using kubectl to the kubernetes cluster
# The pipeline should be executed automatically on merges to the main branch
# The pipeline should be able to be run manually for verification purposes
# The pipeline should be running without errors with all tests passing
# and no output failures from any of the steps
# If there are AWS credentials anywhere in any of the pipelines = FAIL
# If any of the pipelines are failing to run or have failed steps = FAIL
# If any of the pipelines pass when there's a test failure = FAIL
# (will provide steps on how to simulate test failure)
# If the docker image doesn't get uploaded to ECR = FAIL
# If the application isn't successfully running on the cluster = FAIL

name: Backend Continuous Deployment
on:
  push:
    branches:
      - main
    paths:
      - "starter/backend/**"
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.9"

jobs:
  lint:
    # Runs a linting job that fails if the code doesn't adhere to eslint rules
    name: Lint Job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Restore Cache
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: starter/backend/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Install Dependencies
        if: steps.cache.outputs['cache-hit'] != 'true'
        run: npm ci

      - name: Run Lint
        run: npm run lint

  test:
    name: Test Job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Restore Cache
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: starter/backend/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Install Dependencies
        if: steps.cache.outputs['cache-hit'] != 'true'
        run: npm ci

      - name: Run Test
        run: npm run test

  build:
    name: Build Job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    needs: [lint, test]

    # The job should have these steps:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Restore Cache
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: starter/backend/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Install Dependencies
        if: steps.cache.outputs['cache-hit'] != 'true'
        run: npm ci

      - name: Build Application
        run: docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-backend:latest . # && docker run --name mp-backend -p 3000:3000 -d mp-backend]

  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    needs: [lint, test]

    # The job should have these steps:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Restore Cache
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: starter/backend/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Install Dependencies
        if: steps.cache.outputs['cache-hit'] != 'true'
        run: npm ci

      - name: Build Application
        run: docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest . # && docker run --name mp-frontend -p 3000:3000 -d mp-frontend]

