# A Continuous Deployment workflow that:
#     Runs on push against the main branch, only when code in the frontend application changes.
#     Is able to be run on-demand (i.e. manually without needing to push code)
#     Runs the same lint/test jobs as the Continuous Integration workflow
#     Runs a build job only when the lint and test jobs pass
#     The built docker image should be tagged with the git sha
#     Runs a deploy job that applies the Kubernetes manifests to the provided cluster.
#     The manifest should deploy the newly created tagged image
#
#     ⚠️ NOTE Once you begin work on Continuous Deployment,
#       you'll need to first setup the AWS and Kubernetes environment.
#       Follow the next set of instructions when you're ready to start testing your deployments.
