#     Is triggered on pull_requests events against the main branch,
#     Only when code in the frontend application changes
#     Runs the following tasks in parallel:
# There should be a file called .github/workflows/frontend-ci.yaml in the root of the project.

name: CI Pipeline for the Frontend Application
on:
  #   Runs on pull_requests against the main branch,only when code in the frontend application changes.
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
  # Is able to be run on-demand (i.e. manually without needing to push code)
  workflow_dispatch:

env:
  NODE_VERSION: "18.14"

# Runs the following jobs in parallel:
jobs:
  # LINT JOB: There should be a job in the workflow that runs linting.
  lint:
    # Runs a linting job that fails if the code doesn't adhere to eslint rules
    name: Lint Job
    runs-on: ubuntu-latest
    # The job should have these steps:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          # cache: "npm"
          # cache-dependency-path: "**/package-lock.json"

      - name: Restore Cache
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: starter/frontend/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
          # path: path/to/dependencies

      - name: Install Dependencies
        if: steps.cache.outputs['cache-hit'] != 'true'
        run: cd starter/frontend && npm ci
      # Run the npm run lint command
      - name: Run Lint
        run: cd starter/frontend && npm run lint

  # TEST JOB: There should be a job in the workflow that runs the tests The job should have these steps:
  test:
    # Runs a test job that fails if the test suite doesn't pass
    name: Test Job
    runs-on: ubuntu-latest
    # The job should have these steps:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          # cache: "npm"
          # cache-dependency-path: "**/package-lock.json"

      - name: Restore Cache
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: starter/frontend/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
          # path: path/to/dependencies

      - name: Install Dependencies
        if: steps.cache.outputs['cache-hit'] != 'true'
        run: cd starter/frontend && npm ci # Run the npm run test command
      - run: npm run test
    # The two jobs above should run in parallel

  # BUILD JOB: This job should only run after the first 2 succeed (student has to use the "needs" syntax) There should be a step that builds the application using docker. The job should have these steps:
  build:
    # Runs a build job only if the lint and test jobs pass and successfully builds the application
    name: Built Job
    runs-on: ubuntu-latest
    needs: [lint, test]

    # The job should have these steps:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          # cache: "npm"
          # cache-dependency-path: "**/package-lock.json"

      - name: Restore Cache
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: starter/frontend/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
          # path: path/to/dependencies

      - name: Install Dependencies
        if: steps.cache.outputs['cache-hit'] != 'true'
        run: cd starter/frontend && npm ci
      - name: Run Test
        run: cd starter/frontend && npm run test
# The pipeline should be executed automatically on pull_request The pipeline should be able to be run manually The pipeline should be running without errors with all tests passing and no output failures from any of the steps
